import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_URL || '';
const today = () => new Date().toISOString().slice(0, 10);
const emptyRecord = () => ({ record_date: today(), quail_available: '', quail_price: '', quail_sold: '', nattu_available: '', nattu_price: '', nattu_sold: '', meat_available: '', meat_price: '', meat_sold: '', expenses: '', notes: '' });
const money = value => `₹${Number(value || 0).toFixed(2)}`;

async function api(path, options = {}) {
  const response = await fetch(`${API}${path}`, { credentials: 'include', headers: { 'Content-Type': 'application/json' }, ...options });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || 'Request failed');
  return data;
}

const translations = { en: { dashboard: 'Dashboard', entry: 'Daily entry', history: 'History', reports: 'Reports', profile: 'Profile', admin: 'Admin', logout: 'Logout', add: 'Add daily data', save: 'Save record', remaining: 'Remaining stock' }, ta: { dashboard: 'முகப்பு', entry: 'தினசரி பதிவு', history: 'வரலாறு', reports: 'அறிக்கைகள்', profile: 'சுயவிவரம்', admin: 'நிர்வாகம்', logout: 'வெளியேறு', add: 'தினசரி தரவு சேர்க்க', save: 'பதிவை சேமி', remaining: 'மீதமுள்ள இருப்பு' } };

function Login({ onLogin }) {
  const [profiles, setProfiles] = useState([]);
  const [form, setForm] = useState({ email: 'family@poongodifarm.local', password: '', profile_id: '' });
  const [error, setError] = useState('');
  useEffect(() => { api('/api/profiles').then(data => setProfiles(data.profiles)); }, []);
  const submit = async event => { event.preventDefault(); try { onLogin((await api('/api/login', { method: 'POST', body: JSON.stringify(form) })).user); } catch (err) { setError(err.message); } };
  return <main className="auth"><form className="auth-card stack" onSubmit={submit}><div className="logo">PF</div><p className="eyebrow">POONGODI NATURE FARM</p><h1>பூங்கொடி இயற்கை பண்ணை</h1><p className="muted">Family farm management</p>{error && <div className="error">{error}</div>}<label>Family email<input type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} required /></label><label>Password<input type="password" value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} required /></label><label>Select profile<select value={form.profile_id} onChange={event => setForm({ ...form, profile_id: event.target.value })}><option value="">Choose family member</option>{profiles.map(profile => <option value={profile.id} key={profile.id}>{profile.name} · {profile.role}</option>)}</select></label><button className="primary">Enter farm</button></form></main>;
}

function RecordForm({ initial, onDone, onCancel }) {
  const [form, setForm] = useState(initial || emptyRecord());
  const set = (key, value) => setForm({ ...form, [key]: value });
  const calc = group => { const available = Number(form[`${group}_available`] || 0); const sold = Number(form[`${group}_sold`] || 0); const price = Number(form[`${group}_price`] || 0); return { remaining: available - sold, sales: sold * price }; };
  const submit = async event => { event.preventDefault(); if (['quail', 'nattu', 'meat'].some(group => calc(group).remaining < 0)) return alert('Sold quantity cannot exceed available stock.'); try { await api(initial?.id ? `/api/records/${initial.id}` : '/api/records', { method: initial?.id ? 'PUT' : 'POST', body: JSON.stringify(form) }); onDone(); } catch (err) { alert(err.message); } };
  return <form className="panel entry" onSubmit={submit}><div className="section-title"><div><p className="eyebrow">DAILY OPERATIONS</p><h2>{initial ? 'Edit daily record' : 'Add daily data'}</h2></div><button type="button" className="ghost" onClick={onCancel}>Close</button></div><label>Date<input type="date" value={form.record_date} onChange={event => set('record_date', event.target.value)} required /></label>{[['quail', 'Quail eggs'], ['nattu', 'Nattu koli eggs'], ['meat', 'Quail meat (kg)']].map(([group, title]) => { const data = calc(group); return <fieldset key={group}><legend>{title}</legend><div className="form-grid">{[['available', 'Available'], ['price', group === 'meat' ? 'Price / kg (₹)' : 'Price / egg (₹)'], ['sold', group === 'meat' ? 'Sold (kg)' : 'Sold']].map(([kind, label]) => <label key={kind}>{label}<input type="number" min="0" step="0.01" value={form[`${group}_${kind}`]} onChange={event => set(`${group}_${kind}`, event.target.value)} required /></label>)}</div><p className={data.remaining < 0 ? 'calculation invalid' : 'calculation'}>Sales: {money(data.sales)} · Remaining: {Math.max(0, data.remaining)}</p></fieldset>; })}<div className="form-grid"><label>Expenses (₹)<input type="number" min="0" step="0.01" value={form.expenses} onChange={event => set('expenses', event.target.value)} /></label><label className="wide">Farm notes<textarea value={form.notes} onChange={event => set('notes', event.target.value)} rows="3" /></label></div><button className="primary">Save record</button></form>;
}

function Shell({ user, page, setPage, onLogout, lang, setLang, children }) { const text = translations[lang]; const nav = [['dashboard', text.dashboard], ['entry', text.entry], ['history', text.history], ['reports', text.reports], ['profile', text.profile], ...(user.role === 'admin' ? [['admin', text.admin]] : [])]; return <><header><a className="brand"><span className="logo small">PF</span><span>பூங்கொடி இயற்கை பண்ணை<small>Poongodi Nature Farm</small></span></a><nav>{nav.map(([key, label]) => <button className={page === key ? 'active' : ''} onClick={() => setPage(key)} key={key}>{label}</button>)}</nav><div className="user"><span className="avatar">{user.name[0]}</span><span>{user.name}</span><button onClick={onLogout}>{text.logout}</button><button className="language" onClick={() => setLang(lang === 'en' ? 'ta' : 'en')}>{lang === 'en' ? 'தமிழ்' : 'English'}</button></div></header><main className="container">{children}</main></>; }

function Dashboard({ data, setPage, text }) { const cards = [['Quail eggs sold', data.today.quail_sold], ['Nattu eggs sold', data.today.nattu_sold], ['Quail meat sold', `${data.today.meat_sold || 0} kg`], ["Today's total sales", money(data.today.sales)], ["Today's expenses", money(data.today.expenses)], ['Net amount', money(data.today.net)]]; return <><div className="page-heading"><div><p className="eyebrow">{new Date().toLocaleDateString()}</p><h1>Good morning, farm team</h1><p className="muted">A clear view of today's farm rhythm.</p></div><button className="primary" onClick={() => setPage('entry')}>+ {text.add}</button></div><section className="cards">{cards.map(([label, value]) => <article className="stat" key={label}><span>{label}</span><strong>{value || 0}</strong></article>)}</section><section className="panel"><div className="section-title"><h2>{text.remaining}</h2><span className="tag">Live today</span></div><div className="stock">{[['Quail eggs', data.stock.quail_available - data.stock.quail_sold], ['Nattu koli eggs', data.stock.nattu_available - data.stock.nattu_sold], ['Quail meat', `${data.stock.meat_available - data.stock.meat_sold} kg`]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value || 0}</strong></div>)}</div></section></>; }

function History({ records, refresh, onEdit }) { return <section className="panel"><div className="section-title"><h2>Farm history</h2><span>{records.length} records</span></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Quail eggs</th><th>Nattu eggs</th><th>Meat</th><th>Total sales</th><th>Expenses</th><th>Updated by</th><th>Actions</th></tr></thead><tbody>{records.map(row => <tr key={row.id}><td>{row.record_date}</td><td>{row.quail_sold}</td><td>{row.nattu_sold}</td><td>{row.meat_sold} kg</td><td>{money(Number(row.quail_sales) + Number(row.nattu_sales) + Number(row.meat_sales))}</td><td>{money(row.expenses)}</td><td>{row.updated_by_name}</td><td><button className="link" onClick={() => onEdit(row)}>Edit</button><button className="danger link" onClick={async () => { if (confirm('Delete this record?')) { await api(`/api/records/${row.id}`, { method: 'DELETE' }); refresh(); } }}>Delete</button></td></tr>)}</tbody></table></div></section>; }

function Reports() { const [period, setPeriod] = useState('daily'); const [report, setReport] = useState({}); useEffect(() => { api(`/api/reports?period=${period}`).then(data => setReport(data.report)); }, [period]); return <><div className="page-heading"><div><p className="eyebrow">INSIGHTS</p><h1>Reports</h1></div><div className="tabs">{['daily', 'weekly', 'monthly'].map(value => <button className={period === value ? 'active' : ''} onClick={() => setPeriod(value)} key={value}>{value}</button>)}</div></div><section className="cards">{[['Total quail eggs sold', report.quail_sold], ['Total Nattu eggs sold', report.nattu_sold], ['Total quail meat sold', `${report.meat_sold || 0} kg`], ['Total sales', money(report.sales)], ['Total expenses', money(report.expenses)], ['Net profit', money(report.net)]].map(([label, value]) => <article className="stat" key={label}><span>{label}</span><strong>{value || 0}</strong></article>)}</section></>; }

function Profile() { const [user, setUser] = useState({}); const [password, setPassword] = useState(''); useEffect(() => { api('/api/profile').then(data => setUser(data.user)); }, []); return <section className="profile-grid"><article className="panel profile-card"><div className="avatar large">{user.name?.[0]}</div><h2>{user.name}</h2><p>{user.email}</p><span className="tag">{user.role}</span></article><form className="panel stack" onSubmit={async event => { event.preventDefault(); await api('/api/profile/password', { method: 'PUT', body: JSON.stringify({ password }) }); setPassword(''); alert('Password changed'); }}><h2>Change password</h2><label>New password<input type="password" minLength="6" value={password} onChange={event => setPassword(event.target.value)} required /></label><button className="primary">Update password</button></form></section>; }

function Admin() { const [data, setData] = useState({ members: [], logs: [] }); const [form, setForm] = useState({ name: '', email: '', password: '', role: 'member' }); const load = () => api('/api/admin').then(setData); useEffect(load, []); return <><div className="page-heading"><div><p className="eyebrow">CONTROL ROOM</p><h1>Family management</h1></div></div><section className="two-column"><form className="panel stack" onSubmit={async event => { event.preventDefault(); await api('/api/admin/users', { method: 'POST', body: JSON.stringify(form) }); setForm({ name: '', email: '', password: '', role: 'member' }); load(); }}><h2>Add family member</h2><label>Name<input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} required /></label><label>Email<input type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} required /></label><label>Temporary password<input type="password" minLength="6" value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} required /></label><label>Role<select value={form.role} onChange={event => setForm({ ...form, role: event.target.value })}><option>member</option><option>admin</option></select></label><button className="primary">Add member</button></form><section className="panel"><h2>Users</h2><div className="table-wrap"><table><tbody>{data.members.map(member => <tr key={member.id}><td>{member.name}<small>{member.email}</small></td><td>{member.role}</td><td>{member.is_active ? 'Active' : 'Inactive'}</td></tr>)}</tbody></table></div></section></section><section className="panel"><h2>Activity log</h2><div className="table-wrap"><table><tbody>{data.logs.map(log => <tr key={log.id}><td>{log.name}</td><td>{log.action}</td><td>{log.created_at}</td></tr>)}</tbody></table></div></section></>; }
+
function App() { const [user, setUser] = useState(undefined); const [page, setPage] = useState('dashboard'); const [lang, setLang] = useState(localStorage.getItem('farm-language') || 'en'); const [data, setData] = useState({ today: {}, stock: {}, history: [], edit: null }); const load = () => api('/api/dashboard').then(result => setData(current => ({ ...current, ...result }))); useEffect(() => { api('/api/session').then(result => { setUser(result.user); if (result.user) load(); }).catch(() => setUser(null)); }, []); useEffect(() => localStorage.setItem('farm-language', lang), [lang]); if (user === undefined) return <div className="loading">Loading farm...</div>; if (!user) return <Login onLogin={next => { setUser(next); load(); }} />; const logout = async () => { await api('/api/logout', { method: 'POST' }); setUser(null); }; const text = translations[lang]; const refresh = () => load(); return <Shell user={user} page={page} setPage={setPage} onLogout={logout} lang={lang} setLang={setLang}>{page === 'dashboard' && <Dashboard data={data} setPage={setPage} text={text} />}{page === 'entry' && <RecordForm initial={data.edit} onDone={() => { load(); setData({ ...data, edit: null }); setPage('dashboard'); }} onCancel={() => { setData({ ...data, edit: null }); setPage('dashboard'); }} />}{page === 'history' && <History records={data.history} refresh={refresh} onEdit={row => { setData({ ...data, edit: row }); setPage('entry'); }} />}{page === 'reports' && <Reports />}{page === 'profile' && <Profile />}{page === 'admin' && <Admin />}</Shell>; }

createRoot(document.getElementById('root')).render(<App />);
